name: "build-push-test"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Build all artifacts
      id: buildAllApks
      uses: eskatos/gradle-command-action@v1.3.3
      with:
        gradle-version: current
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: assembleRelease
    - name: Sign app APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "30.0.3"
    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }}
        packageName: com.denuafhaengige.duahandroid
        releaseFiles: app/release/*.aab
        track: production
        mappingFile: app/build/outputs/mapping/release/mapping.txt
